["%.o"]
deps = ["%.c", "hellomake.h"]
exec = "gcc -c -o $@ $< -I."

[hellomake]
deps = ["hellomake.o", "hellofunc.o"]
exec = "gcc -o $@ $+ -I."

[clean]
exec = "rm -f hellomake hellomake.o hellofunc.o"
