["%.o"]
deps = ["%.c", "hellomake.h"]
exec = "gcc -c -o $@ $< -I."

[hellomake]
deps = ["hellomake.o", "hellofunc.o"]
exec = "gcc -o $@ $+ -I."

[all]
deps = ["hellomake"]

[error]
exec = "false"

[echo]
exec = ": it executed"

[clean]
exec = "rm -f hellomake hellomake.o hellofunc.o"
